version: '3.8'

services:
  records:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - records-db
  records-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=records
      - POSTGRES_PASSWORD=records
      - POSTGRES_DB=records_dev

volumes:
  postgres_data:
