# Generated by Django 4.1.2 on 2022-11-10 22:26

from django.db import migrations, models

import records.models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0005_alter_record_raw_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="comment",
            field=models.TextField(
                default=records.models.Record.get_default_comment, max_length=256
            ),
        ),
    ]
